/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smart.warehouse.views;


public class DashboardForm extends javax.swing.JFrame {

    /**
     * Creates new form DashboardOparatorForm
     */
    private boolean isManager=true;
    public DashboardForm() {
        initComponents();
        pnlManager.setVisible(isManager);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlManager = new java.awt.Panel();
        jplManager = new javax.swing.JPanel();
        btnMDeleteUsers = new javax.swing.JButton();
        btnMMonthlyReports = new javax.swing.JButton();
        btnMCreateOparatorAccounts = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jplOparator = new javax.swing.JPanel();
        btnRegisterUsers = new javax.swing.JButton();
        btnAddNewStorage = new javax.swing.JButton();
        btnCalculateTheBill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMDeleteUsers.setText("Delete Users");
        btnMDeleteUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMDeleteUsersActionPerformed(evt);
            }
        });

        btnMMonthlyReports.setText("Monthly Reports");
        btnMMonthlyReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMMonthlyReportsActionPerformed(evt);
            }
        });

        btnMCreateOparatorAccounts.setText("Create Oparator Account");
        btnMCreateOparatorAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMCreateOparatorAccountsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jplManagerLayout = new javax.swing.GroupLayout(jplManager);
        jplManager.setLayout(jplManagerLayout);
        jplManagerLayout.setHorizontalGroup(
            jplManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplManagerLayout.createSequentialGroup()
                .addComponent(btnMDeleteUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(btnMCreateOparatorAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(btnMMonthlyReports, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jplManagerLayout.setVerticalGroup(
            jplManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnMDeleteUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnMCreateOparatorAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnMMonthlyReports, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnlManagerLayout = new javax.swing.GroupLayout(pnlManager);
        pnlManager.setLayout(pnlManagerLayout);
        pnlManagerLayout.setHorizontalGroup(
            pnlManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplManager, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlManagerLayout.setVerticalGroup(
            pnlManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 50)); // NOI18N
        jLabel1.setText("Dashbord");

        btnRegisterUsers.setText("Register Users");
        btnRegisterUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterUsersActionPerformed(evt);
            }
        });

        btnAddNewStorage.setText("Add New Storage Job");
        btnAddNewStorage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewStorageActionPerformed(evt);
            }
        });

        btnCalculateTheBill.setText("Calculate The Bill");
        btnCalculateTheBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateTheBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jplOparatorLayout = new javax.swing.GroupLayout(jplOparator);
        jplOparator.setLayout(jplOparatorLayout);
        jplOparatorLayout.setHorizontalGroup(
            jplOparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplOparatorLayout.createSequentialGroup()
                .addComponent(btnRegisterUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(btnAddNewStorage, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalculateTheBill, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jplOparatorLayout.setVerticalGroup(
            jplOparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplOparatorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jplOparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegisterUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddNewStorage, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalculateTheBill, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(268, 268, 268))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jplOparator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(jplOparator, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(pnlManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMDeleteUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMDeleteUsersActionPerformed
        DeleteUserForm deleteUserForm=new DeleteUserForm();
        deleteUserForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMDeleteUsersActionPerformed

    private void btnMMonthlyReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMMonthlyReportsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMMonthlyReportsActionPerformed

    private void btnMCreateOparatorAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMCreateOparatorAccountsActionPerformed
       CreateOparetorAccountsForm createOparetorAccountsForm=new CreateOparetorAccountsForm();
       createOparetorAccountsForm.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnMCreateOparatorAccountsActionPerformed

    private void btnRegisterUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterUsersActionPerformed
        RegisterUserForm registerUserForm=new RegisterUserForm();
        registerUserForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegisterUsersActionPerformed

    private void btnAddNewStorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewStorageActionPerformed
        AddNewStorageForm addNewStorageForm=new AddNewStorageForm();
        addNewStorageForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddNewStorageActionPerformed

    private void btnCalculateTheBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateTheBillActionPerformed
       CalculateBillForm calculateBillForm=new CalculateBillForm();
       calculateBillForm.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnCalculateTheBillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewStorage;
    private javax.swing.JButton btnCalculateTheBill;
    private javax.swing.JButton btnMCreateOparatorAccounts;
    private javax.swing.JButton btnMDeleteUsers;
    private javax.swing.JButton btnMMonthlyReports;
    private javax.swing.JButton btnRegisterUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jplManager;
    private javax.swing.JPanel jplOparator;
    private java.awt.Panel pnlManager;
    // End of variables declaration//GEN-END:variables
}